name: Java Backend Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'java-backend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'java-backend/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    
    - name: Build and test with Maven
      run: |
        cd java-backend
        mvn -B clean test
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: java-test-results
        path: java-backend/target/surefire-reports/
    
    - name: Build JAR
      if: github.ref == 'refs/heads/main'
      run: |
        cd java-backend
        mvn -B package -DskipTests
    
    - name: Upload JAR artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: java-backend-jar
        path: java-backend/target/*.jar
